services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./ofs-pg:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'postgres'
    ports:
      - 5432:5432

  auth-microservice:
    build: .
    container_name: subscription-microservice
    image: subscription-microservice
    restart: always
    env_file:
      - config/.env
    ports:
      - 8080:8080